services:
  - type: web
    name: greenbasket-backend
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn app.main:app --host 0.0.0.0 --port 10000
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: greenbasket-db
          property: connectionString
databases:
  - name: greenbasket-db
    engine: postgresql
